services:
  postgres:
    image: postgres:16
    container_name: cashflow-postgres
    environment:
      POSTGRES_DB: cashflow
      POSTGRES_USER: cashflow_user
      POSTGRES_PASSWORD: cashflow_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: